# Generated by Django 6.0.7 on 2026-07-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlatElektromedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_alat', models.CharField(max_length=20, unique=True)),
                ('nama_alat', models.CharField(max_length=100)),
                ('jenis_alat', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=100)),
                ('tahun_pengadaan', models.IntegerField()),
                ('kondisi', models.CharField(choices=[('Baik', 'Baik'), ('Perlu Perawatan', 'Perlu Perawatan'), ('Rusak', 'Rusak')], max_length=30)),
                ('status_kelayakan', models.CharField(max_length=50)),
            ],
        ),
    ]
